import type { MenuItemInput } from "./types";

export const DEFAULT_MENU_ITEMS: MenuItemInput[] = [
    // Breakfast
    { name: "Idli", category: "Breakfast", price: 20, preparedQuantity: 20 },
    { name: "Mini Idli", category: "Breakfast", price: 30, preparedQuantity: 20 },
    { name: "Vada", category: "Breakfast", price: 15, preparedQuantity: 20 },
    { name: "Medu Vada", category: "Breakfast", price: 15, preparedQuantity: 20 },
    { name: "Masala Vada", category: "Breakfast", price: 15, preparedQuantity: 20 },
    { name: "Plain Dosa", category: "Breakfast", price: 40, preparedQuantity: 20 },
    { name: "Kal Dosa", category: "Breakfast", price: 50, preparedQuantity: 20 },
    { name: "Masala Dosa", category: "Breakfast", price: 60, preparedQuantity: 20 },
    { name: "Onion Dosa", category: "Breakfast", price: 65, preparedQuantity: 20 },
    { name: "Podi Dosa", category: "Breakfast", price: 65, preparedQuantity: 20 },
    { name: "Set Dosa", category: "Breakfast", price: 60, preparedQuantity: 20 },
    { name: "Rava Dosa", category: "Breakfast", price: 70, preparedQuantity: 20 },
    { name: "Rava Masala Dosa", category: "Breakfast", price: 80, preparedQuantity: 20 },
    { name: "Pongal", category: "Breakfast", price: 50, preparedQuantity: 20 },
    { name: "Ghee Pongal", category: "Breakfast", price: 60, preparedQuantity: 20 },
    { name: "Ven Pongal", category: "Breakfast", price: 50, preparedQuantity: 20 },
    { name: "Poori", category: "Breakfast", price: 40, preparedQuantity: 20 },
    { name: "Poori Masala", category: "Breakfast", price: 50, preparedQuantity: 20 },
    { name: "Chapati", category: "Breakfast", price: 30, preparedQuantity: 20 },
    { name: "Vegetable Chapati Kurma", category: "Breakfast", price: 40, preparedQuantity: 20 },
    { name: "Upma", category: "Breakfast", price: 30, preparedQuantity: 20 },
    { name: "Rava Upma", category: "Breakfast", price: 30, preparedQuantity: 20 },
    { name: "Semiyaa Upma", category: "Breakfast", price: 35, preparedQuantity: 20 },
    { name: "Kichadi", category: "Breakfast", price: 40, preparedQuantity: 20 },
    { name: "Lemon Rice", category: "Breakfast", price: 40, preparedQuantity: 20 },
    { name: "Tamarind Rice", category: "Breakfast", price: 40, preparedQuantity: 20 },
    { name: "Curd Rice", category: "Breakfast", price: 30, preparedQuantity: 20 },
    { name: "Bread Toast", category: "Breakfast", price: 20, preparedQuantity: 20 },
    { name: "Bread Omelette (Veg)", category: "Breakfast", price: 30, preparedQuantity: 20 },
    { name: "Filter Coffee", category: "Breakfast", price: 15, preparedQuantity: 20 },
    { name: "Tea", category: "Breakfast", price: 15, preparedQuantity: 20 },
    { name: "Boost / Horlicks / Badam Milk", category: "Breakfast", price: 25, preparedQuantity: 20 },

    // Lunch
    { name: "South Indian Veg Meals", category: "Lunch", price: 100, preparedQuantity: 20 },
    { name: "Mini Meals", category: "Lunch", price: 80, preparedQuantity: 20 },
    { name: "Full Meals", category: "Lunch", price: 120, preparedQuantity: 20 },
    { name: "Special Meals", category: "Lunch", price: 150, preparedQuantity: 20 },
    { name: "Tomato Rice", category: "Lunch", price: 50, preparedQuantity: 20 },
    { name: "Lemon Rice", category: "Lunch", price: 50, preparedQuantity: 20 },
    { name: "Curd Rice", category: "Lunch", price: 40, preparedQuantity: 20 },
    { name: "Vegetable Biryani", category: "Lunch", price: 90, preparedQuantity: 20 },
    { name: "Coconut Rice", category: "Lunch", price: 60, preparedQuantity: 20 },
    { name: "Sambar Rice", category: "Lunch", price: 60, preparedQuantity: 20 },
    { name: "Rasam Rice", category: "Lunch", price: 50, preparedQuantity: 20 },
    { name: "Vatha Kuzhambu Rice", category: "Lunch", price: 60, preparedQuantity: 20 },
    { name: "Vegetable Fried Rice", category: "Lunch", price: 100, preparedQuantity: 20 },
    { name: "Paneer Fried Rice", category: "Lunch", price: 120, preparedQuantity: 20 },
    { name: "Ghee Rice", category: "Lunch", price: 90, preparedQuantity: 20 },
    { name: "Vegetable Pulao", category: "Lunch", price: 90, preparedQuantity: 20 },
    { name: "Chapati", category: "Lunch", price: 30, preparedQuantity: 20 },
    { name: "Butter Chapati", category: "Lunch", price: 35, preparedQuantity: 20 },
    { name: "Phulka", category: "Lunch", price: 30, preparedQuantity: 20 },
    { name: "Vegetable Kurma", category: "Lunch", price: 60, preparedQuantity: 20 },
    { name: "Paneer Butter Masala", category: "Lunch", price: 110, preparedQuantity: 20 },
    { name: "Paneer Kurma", category: "Lunch", price: 100, preparedQuantity: 20 },
    { name: "Mixed Veg Curry", category: "Lunch", price: 90, preparedQuantity: 20 },
    { name: "Aloo Gobi", category: "Lunch", price: 90, preparedQuantity: 20 },
    { name: "Poriyal (Beans / Carrot / Cabbage)", category: "Lunch", price: 40, preparedQuantity: 20 },
    { name: "Kootu", category: "Lunch", price: 40, preparedQuantity: 20 },
    { name: "Avial", category: "Lunch", price: 50, preparedQuantity: 20 },
    { name: "Appalam", category: "Lunch", price: 10, preparedQuantity: 20 },
    { name: "Pickle", category: "Lunch", price: 0, preparedQuantity: 20 },
    { name: "Butter Milk", category: "Lunch", price: 20, preparedQuantity: 20 },

    // Snacks
    { name: "Bajji", category: "Snacks", price: 20, preparedQuantity: 20 },
    { name: "Bonda", category: "Snacks", price: 20, preparedQuantity: 20 },
    { name: "Onion Pakoda", category: "Snacks", price: 25, preparedQuantity: 20 },
    { name: "Sundal", category: "Snacks", price: 20, preparedQuantity: 20 },
    { name: "Samosa", category: "Snacks", price: 15, preparedQuantity: 20 },
    { name: "Veg Cutlet", category: "Snacks", price: 25, preparedQuantity: 20 },
    { name: "Bread Bajji", category: "Snacks", price: 25, preparedQuantity: 20 },
    { name: "Chilli Bajji", category: "Snacks", price: 20, preparedQuantity: 20 },
    { name: "Masala Corn", category: "Snacks", price: 30, preparedQuantity: 20 },
    { name: "Paniyaram", category: "Snacks", price: 40, preparedQuantity: 20 },
    { name: "Sweet Paniyaram", category: "Snacks", price: 40, preparedQuantity: 20 },

    // Dinner
    { name: "Plain Dosa", category: "Dinner", price: 40, preparedQuantity: 20 },
    { name: "Kal Dosa", category: "Dinner", price: 50, preparedQuantity: 20 },
    { name: "Masala Dosa", category: "Dinner", price: 60, preparedQuantity: 20 },
    { name: "Onion Dosa", category: "Dinner", price: 65, preparedQuantity: 20 },
    { name: "Podi Dosa", category: "Dinner", price: 65, preparedQuantity: 20 },
    { name: "Rava Dosa", category: "Dinner", price: 70, preparedQuantity: 20 },
    { name: "Set Dosa", category: "Dinner", price: 60, preparedQuantity: 20 },
    { name: "Uthappam", category: "Dinner", price: 50, preparedQuantity: 20 },
    { name: "Onion Uthappam", category: "Dinner", price: 60, preparedQuantity: 20 },
    { name: "Vegetable Uthappam", category: "Dinner", price: 65, preparedQuantity: 20 },
    { name: "Idiyappam", category: "Dinner", price: 40, preparedQuantity: 20 },
    { name: "Idiyappam Kurma", category: "Dinner", price: 50, preparedQuantity: 20 },
    { name: "Appam", category: "Dinner", price: 40, preparedQuantity: 20 },
    { name: "Appam Stew", category: "Dinner", price: 60, preparedQuantity: 20 },
    { name: "Parotta (Veg)", category: "Dinner", price: 25, preparedQuantity: 20 },
    { name: "Panel Gravy", category: "Dinner", price: 100, preparedQuantity: 20 }, // Corrected "Paneer Gravy" based on context but user list says Paneer Gravy
];
